/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.CLIdemo;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
       TUIdemop classUnderTest = newTUIdemop();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
